name: Build and Push

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

env:
  IMAGE_NAME: clansty/deepin-riscv

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        # with:
        #   image: ghcr.io/clansty/binfmt:latest
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Tag List
        run: |
          echo "TAGS<<EOF" >> $GITHUB_ENV

          DATE="$(date +'%Y%m%d')"
          echo ghcr.io/$IMAGE_NAME:$DATE.$RUN_ID >> $GITHUB_ENV
          echo ghcr.io/$IMAGE_NAME:latest >> $GITHUB_ENV

          echo "EOF" >> $GITHUB_ENV
        env:
          RUN_ID: ${{ github.run_id }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/riscv64
          push: true
          tags: ${{ env.TAGS }}
      - uses: gautamkrishnar/keepalive-workflow@v1
